### ISSUE TITLE
[Feature] Filtering buffer list

### ISSUE THREAD

**Issue by lcrockett** [sidebar-nvim/sidebar.nvim#30]
The buffer list currently lists all buffers that have been opened. It would be nice if we could filter out buffer names (including the use of wildcards, or even better, regexes) so they don't show up in the buffer list anymore. For instance buffers created by plugins such as `nvim-tree` or `minimap`.

Additionally it would be nice if the buffer list could show all opened, non-hidden, non-terminal buffers by default. It seems that at this point I first have to traverse the buffer before it shows up in the sidebar listing, even though the buffer was already opened. Mind you that I lazy load sidebar (using `packer.nvim`) and that it may affect this behaviour.

**Comment by davysson** [comment]
We added the option to ignore buffers via regex, you can already check it in `dev`. You can pass a regex to ignore certain buffers like this `buffers = { ignored_buffers = { "NeogitStatus", ".+#toggleterm#.+" } }`.

About your second point, I wasn't able to replicate this behavior. Are you using any bufferline plugins like barbar to see the buffers? Because they usually save a list of opened buffers between sessions and show them even if the buffer isn't currently open.

**Comment by GustavoKatel** [comment]
hi @lcrockett we are using Lua patterns to match the ignored patterns. So for this case (`neo-tree`), you need to escape the dash. i.e.: `neo%-tree`

**Comment by lcrockett** [comment]
Thanks @GustavoKatel, using `neo%-tree *` did the trick. Leaving this issue open for the second point mentioned in the first message. Cheers

**Comment by GustavoKatel** [comment]
hi @lcrockett I just merged this feature to `dev`

there are two new options for the `buffers` section (see: https://github.com/sidebar-nvim/sidebar.nvim/blob/dev/doc/general.md#buffers)

These are the defaults:
```
ignore_not_loaded = false, -- whether to ignore not loaded buffers
ignore_terminal = true, -- whether to show terminal buffers in the list
```

I think this should be enough to achieve what you want. Please close this issue if it's all good. If not, happy to discuss more.

I'm planning to merge to `main` tomorrow or Tue.

**Comment by lcrockett** [comment]
Both options work like a charm, cheers on the changes !
