### ISSUE TITLE
Error for symbols section

### ISSUE THREAD

**Issue by muhmud** [sidebar-nvim/sidebar.nvim#58]
**Describe the bug**
Getting an error when the sidebar is open on a bash script using `bashls` LSP server.

**To Reproduce**
1. With `bashls` installed, open up a bash script, with the sidebar using the `symbols` section

**Expected behavior**
There should be no errors. The errors come up continuously, making it impossible to edit. 

**Screenshots**
![image](https://user-images.githubusercontent.com/7550982/161077118-f8c3243c-f776-411f-b037-007121378bec.png)

**Environment (please complete the following information):**
 - nvim version - 0.6.1

**Comment by xaltsc** [comment]
I'm experiencing the same problem with Python files.

**Comment by LoricAndre** [comment]
The issue seems be due to changes in the neovim lsp api (my version is `NVIM v0.8.0-dev+69-gee85d8d75`). Apparently the parameters are in the wrong order in the handler [here](https://github.com/sidebar-nvim/sidebar.nvim/blob/90123bf8d4255016f06ef0a5de0617da77b83fc8/lua/sidebar-nvim/builtin/symbols.lua#L96).
When inspecting the request results, it seems that the symbols are stored in the `method` field.
I can open a PR using the line `if has('nvim-0.5.1') == 1` to include version 0.8.0, but it doesn't seem that robust...

**Comment by davysson** [comment]
This should now be fixed on main. Thanks to @LoricAndre
